In [1]:
import numpy as np

In [2]:
a = np.array((3,4,5))

In [3]:
b = np.array((6,7,8))

In [5]:
print(np.dot(a,b))

86


In [6]:
x = np.matrix([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])

In [7]:
x.shape

(4, 4)

In [8]:
k = np.matrix([[1,2,3],[4,5,6]])

In [9]:
m = np.matrix([[7,9,11],[8,10,12]])

In [10]:
m=m.T

In [11]:
m

matrix([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [12]:
k*m

matrix([[ 58,  64],
        [139, 154]])

## PART-2

In [13]:
x = np.matrix([[1,3,1],[2,2,1],[3,5,3]])

In [14]:
x

matrix([[1, 3, 1],
        [2, 2, 1],
        [3, 5, 3]])

In [17]:
x.shape

(3, 3)

In [19]:
np.linalg.matrix_rank(x)

3

In [20]:
x = np.matrix([[1,2,3],[3,2,1],[1,1,1]])

In [21]:
np.linalg.matrix_rank(x)

2

# Going from 2D to nD : Part1