In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
b= np.array([[1,2,3],[4,5,6]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('int32')

In [8]:
b.ndim

2

In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
c = range(10000)

In [12]:
%timeit [i**3 for i in c]

2.65 ms ± 110 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
c_numpy = np.arange(10000)

In [14]:
%timeit c_numpy**3

57 μs ± 1.72 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [15]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [16]:
%timeit list(map(lambda x,y: x*y, l1,l2))

3.31 ms ± 82.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
a1=np.array(l1)
b1=np.array(l2)

In [18]:
%timeit a1*b1

20.8 μs ± 945 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [19]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [25]:
np.full((3,3),2.2,dtype=int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [26]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
v = np.array([1,2,3])

In [28]:
v

array([1, 2, 3])

In [29]:
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [31]:
np.random.random()

0.8701961728590977

In [32]:
50*np.random.random()+2

37.91601157728906

In [33]:
np.random.random([3,3])

array([[1.58162978e-01, 9.14812221e-01, 8.49417803e-01],
       [1.17574122e-04, 7.38058245e-01, 8.41610858e-01],
       [2.02370296e-02, 4.32997079e-01, 5.01024567e-01]])

# Part2

In [34]:
a=np.linspace(1,50,100)

In [35]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [36]:
a.itemsize

8

In [37]:
np.arange(18).shape

(18,)

In [38]:
b=np.arange(18).reshape(2,3,-1)

In [39]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [40]:
a=np.array([2,4,6,8,10,12,14,16])

In [41]:
a[0]

2

In [42]:
a[2]

6

In [43]:
# a[2,4,6]

In [44]:
a[[2,4,6]]

array([ 6, 10, 14])

In [45]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [46]:
a[2:5]

array([ 6,  8, 10])

In [47]:
a[0::]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [48]:
a[0::2]

array([ 2,  6, 10, 14])

In [49]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
a[2,2]

9

In [51]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [52]:
a[(a>2) &(a<5)]

array([3, 4])

In [54]:
b=np.arange(18).reshape(3,1,-1)
print(b)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]]


In [55]:
a=np.arange(10)

In [56]:
b=a

In [58]:
id(b)

2910050464752

In [59]:
id(a)

2910050464752

In [60]:
b[0] = 11

In [61]:
a[0] 

11

In [62]:
np.shares_memory(a,b)

True

In [68]:
a = np.arange(12)

In [69]:
b = a.copy()

In [70]:
np.shares_memory(a,b)

False

In [83]:
a.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [84]:
a.reshape(2,3,2).T

array([[[ 0,  6],
        [ 2,  8],
        [ 4, 10]],

       [[ 1,  7],
        [ 3,  9],
        [ 5, 11]]])

In [85]:
a = np.array([[1,2,3],[4,5,6]])

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
b = np.array([[7,8,9],[10,11,12]])

In [90]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [91]:
a==b

array([[False, False, False],
       [False, False, False]])

In [93]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [95]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [96]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [97]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [98]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [99]:
np.sum(a)

21

In [100]:
np.median(a)

3.5

In [101]:
a.std()

1.707825127659933

In [102]:
a = np.arange(1,10).reshape(3,3)

In [103]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
np.linalg.det(a)

-9.51619735392994e-16

In [105]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [106]:
np.linalg.eig(a)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

In [107]:
b=a.T

In [108]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [109]:
a = np.array([1,1,0],dtype = bool)
b = np.array([1,0,1],dtype = bool)

In [110]:
np.logical_or(a,b)

array([ True,  True,  True])

In [111]:
a

array([ True,  True, False])

In [112]:
np.logical_and(a,b)

array([ True, False, False])

In [113]:
np.all(a==a)

True

In [114]:
a = np.array([[1,2],[3,4]])

In [115]:
a.sum()

10

In [116]:
a.sum(axis =0)

array([4, 6])

In [117]:
a.sum(axis = 1)

array([3, 7])

In [118]:
a.max()

4

In [119]:
a.argmax()

3

In [120]:
a.shape

(2, 2)

In [124]:
a = np.arange(1,10)

In [125]:
a.shape

(9,)

In [126]:
a[:,np.newaxis].shape

(9, 1)

In [127]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])